title: Zixi Liu # your name (or website title) here
logo: "/images/selfie.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I am currently an Master Student in Urban Spatial Analytics at University of Pennsylvania. I am interested in data-driven mathematical modeling and statistical inference of the impact of environmental risk factors on health disparity issues. 
  <br><br>
  <br><br>
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
